# Generated by Django 5.2.4 on 2025-07-31 16:15

import discussion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='replyier',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public announcements visible to all users.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Target user for the notification. Leave blank for public announcements.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReplyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('reply', 'Reply'), ('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_interactions', to='discussion.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reply_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reply', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='ReplyToAnotherReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=discussion.models.reply_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=discussion.models.reply_upload_path)),
                ('docs', models.FileField(blank=True, null=True, upload_to=discussion.models.reply_upload_path)),
                ('link', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('general', 'General'), ('question', 'Question'), ('discussion', 'Discussion'), ('feedback', 'Feedback'), ('announcement', 'Announcement')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replyier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToAnotherReplyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('reply', 'Reply'), ('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_another_reply_interactions', to='discussion.replytoanotherreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reply_to_another_reply_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reply', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='ReplytoAReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=discussion.models.reply_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=discussion.models.reply_upload_path)),
                ('docs', models.FileField(blank=True, null=True, upload_to=discussion.models.reply_upload_path)),
                ('link', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('general', 'General'), ('question', 'Question'), ('discussion', 'Discussion'), ('feedback', 'Feedback'), ('announcement', 'Announcement')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='discussion.replytoareply')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to_reply', to='discussion.reply')),
                ('replyier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='replytoanotherreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to_reply', to='discussion.replytoareply'),
        ),
        migrations.CreateModel(
            name='ReplytoReplyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('reply', 'Reply'), ('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_interactions', to='discussion.replytoareply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reply_to_reply_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reply', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='discussion.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Status',
                'verbose_name_plural': 'User  Notification Statuses',
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.CreateModel(
            name='UserPostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('reply', 'Reply'), ('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='discussion.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post', 'interaction_type')},
            },
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
