# Generated by Django 5.2.4 on 2025-08-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_notification_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytoanotherreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to_another_reply', to='discussion.replytoareply'),
        ),
        migrations.AlterField(
            model_name='replytoareply',
            name='content',
            field=models.TextField(default='hi'),
        ),
    ]
