# Generated by Django 5.2.4 on 2025-08-05 12:17

import discussion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_alter_replytoanotherreply_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=discussion.models.user_upload_path),
        ),
        migrations.AddField(
            model_name='reply',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=discussion.models.reply_upload_path),
        ),
        migrations.AddField(
            model_name='replytoareply',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=discussion.models.reply_upload_path),
        ),
    ]
