# Generated by Django 4.2.23 on 2025-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_post_image2_reply_image2_replytoareply_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRagCorpusStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.CharField(max_length=100, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('total_posts_indexed', models.IntegerField(default=0)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRagFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(help_text='Discussion post ID', unique=True)),
                ('rag_file_name', models.CharField(help_text='Full Vertex AI File name (e.g., projects/.../ragFiles/123)', max_length=500)),
                ('rag_file_id', models.CharField(help_text='Just the file ID (e.g., 5509377323857763591)', max_length=100)),
                ('display_name', models.CharField(help_text='Display name in Vertex AI', max_length=255)),
                ('local_file_path', models.CharField(help_text='Path to local JSON file', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA256 hash of file content', max_length=64)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('needs_update', models.BooleanField(default=False)),
                ('last_sync_error', models.TextField(blank=True, help_text='Last error message if any')),
            ],
            options={
                'verbose_name': 'AI RAG File',
                'verbose_name_plural': 'AI RAG Files',
                'indexes': [models.Index(fields=['post_id'], name='discussion__post_id_5f215f_idx'), models.Index(fields=['rag_file_id'], name='discussion__rag_fil_a065ae_idx')],
            },
        ),
    ]
