# Generated by Django 4.2.23 on 2026-03-30 04:16

import discussion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0005_airagcorpusstats_airagfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='One-line description shown in preview cards', max_length=300)),
                ('body', models.TextField(help_text='Full story content ,  markdown/plain text supported')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=discussion.models.story_cover_upload_path)),
                ('tag', models.CharField(choices=[('admission', 'Admission Journey'), ('scholarship', 'Scholarship'), ('visa', 'Visa Experience'), ('campus_life', 'Campus Life'), ('summer_program', 'Summer Program'), ('tips', 'Tips & Advice'), ('other', 'Other')], default='other', max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
